### ISSUE TITLE
Best Editor

### ISSUE THREAD

**Issue by interfaceslivres** [opentibia/item-editor#12]
Hi Comedinha,

I am trying to create an adventure server on OTS. I've never did anything like it, so I would be very glad if you could give me some hints about the bests tools to use.

It is 2015 now, and i could not figure out the best versions of OTS for:

1- Create maps;
2- Create Itens;
3- Create NPCs;
4- Create a server;
5- Create a standalone client that the players would not have to download an ip changer.

Sorry if it is too obvious.
Valeu!

**Comment by assassina** [comment]
Please, if you want help, try https://otland.net/ or http://opentibia.net/. This place is only for reporting bugs/issues.
